### PR TITLE
Adding DigiMesh Support

### PR DESCRIPTION
**Pull request by jamesleesaunders**
Adds XBee Digimesh support by adding a new digimesh.py module.

This is a plain copy of code already on GitHub, credits:

By Matteo Lucchesi, 2011
Inspired by code written by Amit Synderman, Marco Sangalli and Paul Malmsten
matteo@luccalug.it http://matteo.luccalug.it

This module provides an XBee (Digimesh) API library.

Updated by Thom Nichols http://blog.thomnichols.org

### CODE REVIEW

**Comment by jamesleesaunders** [comment]
I have emailed both Matteo Lucchesi and Thom Nichols asking their permission to use their code.

**Comment by thom-nic** [comment]
Yes, happy to have this merged upstream.

**Comment by hansmosh** [comment]
@pmalmsten: thanks for the contribution (and a little nudge through emailing us).

I haven't personally used digimesh but I know it's been highly requested for this library. I'll go ahead and merge this in and we can improve upon as necessary.

**Comment by luk156** [comment]
:+1:

**Comment by jamesleesaunders** [comment]
Thanks for merging this in @hansmosh @pmalmsten :-)

Also huge thanks to @luk156 and @thom-nic for allowing their code to be merged upstream, it is great to see this DigiMesh support added to the main repo.

**Pull request merged**
